import type { MetaFunction } from "@remix-run/node";
import { Link } from "@remix-run/react";

export const meta: MetaFunction = () => [
  { title: "How mosaicrise works" },
  {
    name: "description",
    content:
      "How mosaicrise turns letters to your younger self or a grandparent into a video reply in their voice.",
  },
];

export default function About() {
  return (
    <main className="min-h-screen px-6 py-16 sm:px-8 sm:py-24">
      <div className="mx-auto max-w-2xl">
        <Link
          to="/"
          className="text-sm text-dusk-500 hover:text-dusk-700"
        >
          ← back
        </Link>

        <h1 className="mt-6 font-serif text-4xl leading-[1.15] text-dusk-900 sm:text-5xl">
          How it works.
        </h1>

        <div className="mt-10 space-y-6 text-base leading-relaxed text-dusk-700">
          <section>
            <h2 className="font-serif text-2xl text-dusk-900">1. You name a Subject.</h2>
            <p className="mt-2">
              A younger version of yourself. A grandparent. A great-grandparent.
              Someone who shaped you. You upload a photo, optionally a short
              voice sample, and a few notes about who they were to you.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-dusk-900">2. You write a letter.</h2>
            <p className="mt-2">
              Whatever you want to say to them. Things you wish you could.
              Things you couldn&apos;t when they were here. The letters that
              live in your head.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-dusk-900">3. They write back.</h2>
            <p className="mt-2">
              Within a couple of minutes you receive a short video reply — in
              their voice (if you cloned it), on their face. Generated by AI,
              grounded in what you told us about them.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-2xl text-dusk-900">4. They check in.</h2>
            <p className="mt-2">
              Optional: short scheduled video messages from them, delivered at
              a cadence you choose. &ldquo;Good job today.&rdquo; &ldquo;I&apos;m
              proud of you.&rdquo; &ldquo;Take a breath.&rdquo; In their voice.
            </p>
          </section>
        </div>

        <section className="mt-12 rounded-md border border-dusk-700/15 bg-sand-100 px-6 py-5 text-sm text-dusk-600">
          <h3 className="font-medium text-dusk-900">A note on what this is, and isn&apos;t.</h3>
          <p className="mt-2">
            mosaicrise is a reflective tool. It&apos;s not therapy and it
            doesn&apos;t replace one. Voice cloning of another person requires
            explicit consent — yours, the estate&apos;s, or a living
            person&apos;s. Your letters, replies, and uploaded materials are
            private to you. We never share them.
          </p>
        </section>

        <section className="mt-10 text-sm text-dusk-500">
          <p>
            Currently in invite-only beta.{" "}
            <a
              className="underline hover:text-dusk-700"
              href="mailto:hello@mosaicrise.com?subject=mosaicrise%20invite%20request"
            >
              Request an invite
            </a>
            .
          </p>
        </section>

        <footer className="mt-24 border-t border-dusk-700/15 pt-6 text-xs text-dusk-500">
          Phase 0 build · scaffolding only · invite-only beta opens later this year
        </footer>
      </div>
    </main>
  );
}
